import { index, route, type RouteConfig } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("series", "routes/catalog.tsx", { id: "series-catalog" }),
  route("movies", "routes/catalog.tsx", { id: "movies-catalog" }),
  route("series/:id", "routes/series-detail.tsx", { id: "series-detail" }),
  route("series/:id/season/:number", "routes/series-detail.tsx", { id: "series-season-detail" }),
  route("movies/:id", "routes/movie-detail.tsx"),
  route("search", "routes/search.tsx"),
  route("watch/episode/:id", "routes/watch-episode.tsx"),
  route("watch/movie/:id", "routes/watch-movie.tsx"),
  route("login", "routes/login.tsx"),
  route("favorites", "routes/favorites.tsx"),
  route("history", "routes/history.tsx"),
  route("admin", "routes/admin-dashboard.tsx"),
  route("admin/catalog", "routes/admin-catalog-index.tsx"),
  route("admin/catalog/series", "routes/admin-catalog-list.tsx", { id: "admin-catalog-series" }),
  route("admin/catalog/movies", "routes/admin-catalog-list.tsx", { id: "admin-catalog-movies" }),
  route("admin/catalog/series/new", "routes/admin-catalog-form.tsx", { id: "admin-series-new" }),
  route("admin/catalog/series/:seriesId", "routes/admin-series-workspace.tsx"),
  route("admin/catalog/series/:seriesId/edit", "routes/admin-catalog-form.tsx", { id: "admin-series-edit" }),
  route("admin/catalog/series/:seriesId/seasons/new", "routes/admin-catalog-form.tsx", { id: "admin-season-new" }),
  route("admin/catalog/series/:seriesId/seasons/:seasonId", "routes/admin-season-workspace.tsx"),
  route("admin/catalog/series/:seriesId/seasons/:seasonId/edit", "routes/admin-catalog-form.tsx", { id: "admin-season-edit" }),
  route("admin/catalog/series/:seriesId/seasons/:seasonId/episodes/new", "routes/admin-catalog-form.tsx", { id: "admin-episode-new" }),
  route("admin/catalog/series/:seriesId/seasons/:seasonId/episodes/:episodeId/edit", "routes/admin-catalog-form.tsx", { id: "admin-episode-edit" }),
  route("admin/catalog/movies/new", "routes/admin-catalog-form.tsx", { id: "admin-movie-new" }),
  route("admin/catalog/movies/:movieId/edit", "routes/admin-catalog-form.tsx", { id: "admin-movie-edit" }),
  route("admin/sources", "routes/admin-sources.tsx"),
  route("admin/sources/new", "routes/admin-source-form.tsx", { id: "admin-source-new" }),
  route("admin/sources/:sourceId/edit", "routes/admin-source-form.tsx", { id: "admin-source-edit" }),
  route("admin/subtitles", "routes/admin-subtitles.tsx"),
  route("admin/subtitles/new", "routes/admin-subtitle-form.tsx", { id: "admin-subtitle-new" }),
  route("admin/subtitles/:subtitleId/edit", "routes/admin-subtitle-form.tsx", { id: "admin-subtitle-edit" }),
  route("admin/danmaku", "routes/admin-danmaku.tsx"),
  route("admin/audit", "routes/admin-audit.tsx"),
  route("*", "routes/not-found.tsx"),
] satisfies RouteConfig;
